CREATE DATABASE casino;
USE casino;


CREATE TABLE ROL (
  ROL_ID INT PRIMARY KEY IDENTITY(1,1),
  ROL_NOMBRE VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE WALLET (
  WALLET_ID INT PRIMARY KEY IDENTITY(1,1),
  WALLET_BALANCE FLOAT
);

CREATE TABLE USUARIO (
  USU_ID INT PRIMARY KEY IDENTITY(1,1),
  USU_USERNAME VARCHAR(30) UNIQUE NOT NULL,
  USU_EMAIL VARCHAR(100) UNIQUE NOT NULL,
  USU_PASSWORD VARCHAR(25) NOT NULL,
  USU_SALDO FLOAT,
  ROL_ID INT,
  WALLET_ID INT,
  FOREIGN KEY (ROL_ID) REFERENCES ROL(ROL_ID),
  FOREIGN KEY (WALLET_ID) REFERENCES WALLET(WALLET_ID)
);



CREATE TABLE JUEGO (
  JUE_ID INT PRIMARY KEY IDENTITY(1,1),
  JUE_NOMBRE VARCHAR(255) NOT NULL,
  JUE_DESCRIPCION VARCHAR(500),
  JUE_MIN_APUESTA FLOAT,
  JUE_MAX_APUESTA FLOAT,
  JUE_TIEMPO_JUEGO INT
);


CREATE TABLE APUESTA (
  APU_ID INT PRIMARY KEY IDENTITY(1,1),
  APU_NOMBRE VARCHAR(30) UNIQUE NOT NULL,
  APU_VALOR FLOAT
);


CREATE TABLE NOTIFICACION (
  NOT_ID INT PRIMARY KEY IDENTITY(1,1),
  NOT_USUARIO_ID INT,
  NOT_CONTENIDO VARCHAR(500),
  NOT_TIEMPO DATETIME DEFAULT GETDATE(),
  FOREIGN KEY (NOT_USUARIO_ID) REFERENCES USUARIO(USU_ID)
);


CREATE TABLE JUGADA (
  JUG_ID INT PRIMARY KEY IDENTITY(1,1),
  JUG_USUARIO_ID INT,
  JUG_JUEGO_ID INT,
  JUG_APUESTA_ID INT,
  JUG_TIEMPO_APUESTA DATETIME DEFAULT GETDATE(),
  JUG_CANTIDAD FLOAT,
  FOREIGN KEY (JUG_USUARIO_ID) REFERENCES USUARIO(USU_ID),
  FOREIGN KEY (JUG_JUEGO_ID) REFERENCES JUEGO(JUE_ID),
  FOREIGN KEY (JUG_APUESTA_ID) REFERENCES APUESTA(APU_ID)
);

CREATE TABLE TRANSACCION (
  TRA_ID INT PRIMARY KEY IDENTITY(1,1),
  TRA_USUARIO_ID INT,
  TRA_MONTO FLOAT,
  TRA_TIPO VARCHAR(50),
  TRA_TIEMPO DATETIME DEFAULT GETDATE(),
  FOREIGN KEY (TRA_USUARIO_ID) REFERENCES USUARIO(USU_ID)
);


CREATE TABLE VERIFICACION (
  VER_ID INT PRIMARY KEY IDENTITY(1,1),
  VER_UserID INT,
  VER_DOCUMENTOTIPO VARCHAR(100),
  VER_DOCUMENTONUMERO VARCHAR(100),
  VER_ESTADO BIT,
  VER_FECHA TIMESTAMP,
  FOREIGN KEY (VER_UserID) REFERENCES USUARIO(USU_ID)
);
